---

# Boolean (or any value convertible using the bool filter in Ansible)
# indicating whether system packages should be upgraded (i.e. the equivalent
# of yum update -y). Should default to false if not given.
cluster_upgrade_system_packages: false

# Default nfs configuration
nfs_fstype: "xfs"
nfs_disk_location: "/dev/sdb"
nfs_export: "/srv/home"

# Jasmin Homedir
jasmin_homedir: "/home/users"
