---
# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of compute node instances, and configure it
# for a BeeGFS server

- hosts: openstack
  pre_tasks:
    - name: Import discover-gateway-ip.yml
      import_tasks: tasks/discover-gateway-ip.yml
  roles:
    - role: jasmin.cluster-infra
      cluster_groups: "{{ beegfs_groups + [cluster_gw] }}"
      cluster_tag: "{{ cluster_type.storage }}"
  tasks:
    - name: add beegfs cluster to beegfs_servers group
      add_host:
       name: "{{ item }}"
       groups: beegfs_servers
      loop: "{{ groups['mds'] + groups['oss'] }}"

- hosts: beegfs_servers
  become: true
  tasks:
    - set_fact:
        beegfs_name: "{{ cluster_name }}"
    - import_tasks: cluster-hosts.yml
    - import_tasks: cluster-firewalld.yml

- import_playbook: beegfs.yml

- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      cluster_groups: "{{ beegfs_groups }}"
      cluster_tag: "{{ cluster_type.storage }}"
      cluster_stack_update_only: true

  # Hack pending outcome of:
  # - https://github.com/ansible/ansible/pull/53757
  # - https://review.openstack.org/643195
  tasks:
    - name: Fixup stack tags
      command: "openstack stack update --existing --tags {{ cluster_type.storage }} {{ cluster_name }}"
