---

# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of compute node instances, and configure it
# for a BeeGFS server

- hosts: openstack
  tasks:
    - import_tasks: tasks/install-dependencies.yml
    - import_tasks: tasks/infra/provision.yml
      vars:
        cluster_groups: "{{ beegfs_groups }}"
        cluster_tag: "{{ cluster_type.storage }}"
    - name: Add servers to beegfs_servers group
      add_host:
        name: "{{ item }}"
        groups: beegfs_servers
      loop: "{{ groups.get('mds', []) + groups.get('oss', []) }}"

- hosts: beegfs_servers
  become: true
  tasks:
    - set_fact:
        beegfs_name: "{{ cluster_name }}"
    - import_tasks: cluster-hosts.yml
    - import_tasks: cluster-firewalld.yml

- import_playbook: beegfs.yml

- hosts: beegfs_servers
  tasks:
    - include: tasks/update.yml

- hosts: openstack
  tasks:
    - import_tasks: tasks/infra/cleanup-gateway.yml
      vars:
        cluster_groups: "{{ beegfs_groups }}"
        cluster_tag: "{{ cluster_type.storage }}"
