---
# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of baremetal compute node instances, and configure it
# for a SLURM partition
- hosts: openstack

  roles:
    - role: stackhpc.cluster-infra
      cluster_name: "{{ cluster_name }}"
      cluster_params:
        cluster_prefix: "{{ cluster_name }}"
        cluster_keypair: "{{ cluster_keypair }}"
        cluster_groups: "{{ cluster_groups }}"
        cluster_net: "{{ cluster_net }}"
#       node_resource: "instance.yaml"
        #node_resource: "Cluster::Instance"
        #cluster_config_drive: "{{ cluster_config_drive | default(false) }}"
      cluster_roles: "{{ cluster_roles }}"
      cluster_environment_nodenet: "{{ role_path }}/files/environments/{{ cluster_nodenet_environment | default('nodenet-1.yaml') }}"
