---

# Provision the cluster infrastructure
- hosts: openstack
  pre_tasks:
    - name: Ensure fixed IP is given
      fail:
        msg: "Freeipa server requires a fixed external IP"
      when: cluster_fixed_ip is not defined
  tasks:
    - import_tasks: tasks/install-dependencies.yml
    - import_tasks: tasks/infra/provision.yml
      vars:
        # These are the groups to use when no fixed IP is given
        cluster_groups: "{{ freeipa_groups_no_ip }}"
        # This is the gateway group to use when a fixed IP is given
        cluster_gw_group_fixed_ip: "{{ freeipa_gw_group_name }}"
        # These are the groups to use when a fixed IP is given
        cluster_groups_fixed_ip: "{{ freeipa_groups_fixed_ip }}"
        # Tag to assign to the cluster
        cluster_tag: "{{ cluster_type.freeipa }}"
    - import_tasks: tasks/infra/os-project-name.yml

# Set up the networking
- hosts: cluster
  become: true
  tasks:
    - import_tasks: tasks/network/hosts.yml
    - import_tasks: tasks/network/firewall.yml

- hosts: freeipa_servers
  become: true
  tasks:
    - import_tasks: tasks/infra/os-project-name.yml
    - import_tasks: tasks/freeipa/server.yml
      vars:
        freeipa_domain: "{{ openstack_project_name | lower }}.local"
        freeipa_realm: "{{ openstack_project_name | upper }}.LOCAL"
        freeipa_ds_password: "{{ freeipa_password }}"
        freeipa_admin_password: "{{ freeipa_password }}"

- hosts: freeipa_proxies
  become: true
  tasks:
    - import_tasks: tasks/freeipa/proxy.yml
  vars:
    freeipa_host: "{{ hostvars[groups['freeipa_servers'] | first] }}"
