---

# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of compute node instances, and configure it
# for a gluster cluster.

- hosts: openstack
  tasks:
    - import_tasks: tasks/install-dependencies.yml
    - import_tasks: tasks/infra/provision.yml
      vars:
        cluster_groups: "{{ gluster_groups }}"
        cluster_tag: "{{ cluster_type.storage }}"

- hosts: cluster
  become: true
  tasks:
    - import_tasks: tasks/network/hosts.yml
    - import_tasks: tasks/network/firewall.yml

- hosts: cluster
  become: true
  roles:
    - role: resmo.ntp

- import_playbook: gluster.yml

- hosts: gluster_servers
  tasks:
    - include: tasks/update.yml

- hosts: openstack
  tasks:
    - import_tasks: tasks/infra/cleanup-gateway.yml
      vars:
        cluster_groups: "{{ gluster_groups }}"
        cluster_tag: "{{ cluster_type.storage }}"
