---

# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of compute node instances, and configure it
# for a gluster cluster.

- hosts: openstack
  tasks:
    - import_tasks: tasks/install-dependencies.yml
    - import_tasks: tasks/infra/provision.yml
      vars:
        cluster_groups: "{{ gluster_groups }}"
        cluster_tag: "{{ cluster_type.storage }}"
    - name: Add servers to gluster_servers group
      add_host:
        name: "{{ item }}"
        groups: gluster_servers
      loop: "{{ groups.get('server', []) }}"

- hosts: cluster
  become: true
  tasks:
    - import_tasks: tasks/cluster-hosts.yml 
    - import_tasks: tasks/cluster-firewalld.yml

- hosts: cluster
  become: true  
  roles:
    - role: resmo.ntp

- import_playbook: gluster.yml

- hosts: gluster_servers
  tasks:
    - include: tasks/update.yml

- hosts: openstack
  tasks:
    - import_tasks: tasks/infra/cleanup-gateway.yml
      vars:
        cluster_groups: "{{ gluster_groups }}"
        cluster_tag: "{{ cluster_type.storage }}"
