---

# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of compute node instances, and configure it
# for a gluster cluster.

- hosts: openstack
  tasks:
    - import_tasks: tasks/install-dependencies.yml

    # Add the identity stack to the cluster and configure it as the gateway
    - include_role:
        name: jasmin.cluster-infra
      vars:
        cluster_name: "{{ identity_stack_name }}"
        cluster_stack_update: false
        cluster_gw_group: "{{ identity_gw_group_name }}"

    # Provision the cluster infrastructure
    - import_tasks: tasks/infra/provision.yml
      vars:
        cluster_groups: "{{ gluster_groups }}"
        cluster_tag: "{{ cluster_type.storage }}"

- hosts: cluster
  become: true
  tasks:
    - import_tasks: tasks/network/hosts.yml
    - import_tasks: tasks/network/firewall.yml
  roles:
    - role: resmo.ntp

# Join the hosts to the FreeIPA realm
- hosts: gluster_servers
  become: true
  tasks:
    - include_tasks: tasks/identity/freeipa/client.yml

# Set the permissions for the cluster in FreeIPA
- hosts: freeipa_servers
  become: true
  tasks:
    - include_tasks: tasks/identity/freeipa/cluster_permissions.yml
  vars:
    # We don't need a group to permit users access to these hosts
    create_users_group: false

- import_playbook: gluster.yml

- hosts: gluster_servers
  tasks:
    - include: tasks/util/upgrade_os_packages.yml
