---

# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of compute node instances, and configure it
# for a gluster cluster.

- hosts: openstack
  tasks:
    - import_tasks: tasks/install-dependencies.yml

    # Add the identity stack to the cluster and configure it as the gateway
    - include_role:
        name: jasmin.cluster-infra
      vars:
        cluster_name: "{{ identity_stack_name }}"
        cluster_stack_update: false
        cluster_gw_group: "{{ identity_gw_group_name }}"

    # Provision the cluster infrastructure
    - import_tasks: tasks/infra/provision.yml
      vars:
        cluster_groups: "{{ gluster_groups }}"
        cluster_tag: "{{ cluster_type.storage }}"

- hosts: cluster
  become: true
  tasks:
    - import_tasks: tasks/network/hosts.yml

- hosts: gluster_servers
  become: true
  tasks:
    - import_tasks: tasks/network/firewall.yml
    - include: tasks/util/upgrade_os_packages.yml
    # Join the hosts to the FreeIPA realm
    - include_tasks: tasks/identity/freeipa/client.yml

# Set the permissions for the cluster in FreeIPA
- hosts: freeipa_servers
  become: true
  tasks:
    - include_tasks: tasks/identity/freeipa/cluster_permissions.yml
  vars:
    # We don't need a group to permit users access to these hosts
    create_users_group: false

- hosts: gluster_servers
  become: true
  pre_tasks:
    # Prevent Gluster servers from failing to start after reboot: IPv6 is disabled
    # via sysctl in the JASMIN CentOS 7 image, but initramfs doesn't include this
    # sysctl setting. This prevents rpcbind (on which gluster depends) from
    # starting on boot. See https://access.redhat.com/solutions/2798411 for more
    # details. Unfortunately the Red Hat solution is incomplete, as dracut doesn't
    # include /etc/sysctl* by default, so we modify dracut.conf before rebuilding.
    - name: Add sysctl configuration to dracut.conf
      lineinfile:
        path: /etc/dracut.conf
        line: install_items="/etc/sysctl.conf /etc/sysctl.d/*"
      register: dracut_configure

    - name: Rebuild initramfs
      command: dracut -f
      when: dracut_configure is changed
  roles:
    - role: jasmin.gluster
      gluster_enable:
        servers: true
        clients: false
      gluster_cluster_storage_group_name: gluster_servers
      # cluster_attached_volumes has a list of device paths
      # The gluster role wants just the device name, i.e. for /dev/sdb, it wants sdb
      gluster_cluster_block_devices: "{{ cluster_attached_volumes | map(attribute = 'device') | map('basename') | list }}"
      gluster_cluster_volume_options:
        cluster.nufa: 'on'
