---

# Provision the cluster infrastructure
- hosts: openstack
  pre_tasks:
    - name: Ensure fixed IP is given
      fail:
        msg: "Fixed external IP is required"
      when: cluster_fixed_ip is not defined
  tasks:
    - import_tasks: tasks/install-dependencies.yml
    - import_tasks: tasks/infra/os-project-name.yml
    - import_tasks: tasks/infra/provision.yml
      vars:
        # These are the groups to use when no fixed IP is given
        cluster_groups: "{{ identity_groups_no_ip }}"
        # This is the gateway group to use when a fixed IP is given
        cluster_gw_group_fixed_ip: "{{ identity_gw_group_name }}"
        # These are the groups to use when a fixed IP is given
        cluster_groups_fixed_ip: "{{ identity_groups_fixed_ip }}"
        # Tag to assign to the cluster
        cluster_tag: "{{ cluster_type.identity }}"

- hosts: cluster
  become: true
  tasks:
    # Set up the networking
    - import_tasks: tasks/network/hosts.yml
    - import_tasks: tasks/network/firewall.yml

- hosts: freeipa_servers
  become: true
  tasks:
    - include_tasks: tasks/identity/freeipa/server.yml

- hosts: identity_proxies
  become: true
  tasks:
    - include_tasks: tasks/identity/freeipa/client.yml
    - include_tasks: tasks/identity/proxy.yml

# Set the permissions for the cluster in FreeIPA
- hosts: freeipa_servers
  become: true
  tasks:
    - include_tasks: tasks/identity/freeipa/cluster_permissions.yml
  vars:
    # We don't need a group to permit users access to these hosts
    create_users_group: false
