---

# Provision the cluster infrastructure
- hosts: openstack
  tasks:
    - import_tasks: tasks/install-dependencies.yml
    - import_tasks: tasks/infra/provision.yml
      vars:
        # These are the groups to use when no fixed IP is given
        cluster_groups: "{{ identity_groups_no_ip }}"
        # This is the gateway group to use when a fixed IP is given
        cluster_gw_group_fixed_ip: "{{ identity_gw_group_name }}"
        # These are the groups to use when a fixed IP is given
        cluster_groups_fixed_ip: "{{ identity_groups_fixed_ip }}"
        # Tag to assign to the cluster
        cluster_tag: "{{ cluster_type.identity }}"

- hosts: cluster
  become: true
  tasks:
    - import_tasks: tasks/network/firewall.yml

# Apply patches on the identity servers only
- hosts: identity_servers
  become: true
  tasks:
    - include_tasks: tasks/util/upgrade_os_packages.yml

- hosts: freeipa_servers
  become: true
  tasks:
    - include_tasks: tasks/identity/freeipa/server.yml

# Enroll the Keycloak and proxy servers as FreeIPA clients
- hosts: keycloak_servers,identity_proxies
  become: true
  tasks:
    - include_tasks: tasks/identity/freeipa/client.yml

# Set the permissions for the cluster in FreeIPA
- hosts: freeipa_servers
  become: true
  tasks:
    - include_tasks: tasks/identity/freeipa/cluster_permissions.yml
  vars:
    # We don't need a group to permit users access to these hosts
    create_users_group: false

- hosts: keycloak_servers
  become: true
  tasks:
    # Use a persistent random string for the Keycloak local admin password
    # All interaction will be by logging in with the FreeIPA admin
    - include_tasks: tasks/util/persistent_random_fact.yml
      vars:
        fact_name: keycloak_admin_password
        random_string_length: 40
    - include_tasks: tasks/identity/keycloak/server.yml
      vars:
        proxy_external_domain: "{{ hostvars[groups.identity_proxies | first].proxy_external_domain }}"

- hosts: identity_proxies
  become: true
  tasks:
    - include_tasks: tasks/identity/proxy.yml
