---
# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of baremetal compute node instances, and configure it
# for a SLURM partition
- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      cluster_network: "caastest-U-internal"

- hosts: openstack
  tasks:
    - block:
        - name: Get stack outputs
          os_stack_outputs:
            stack_id: "{{ storage_name }}"
        - name: Export storage information from stack outputs
          set_fact:
            storage_stack_info: "{{ stack_outputs['info'] | select('ne', '') | map('from_json') | selectattr('storage_type', '==', 'nfs') | first }}"
        - debug:
            msg: "{{ storage_stack_info }}"
      when: storage_name is defined

- hosts:
    - cluster
  become: true
  tasks:
    - import_tasks: cluster-hosts.yml 
    - import_tasks: cluster-firewalld.yml 

- hosts:
    - cluster
  become: true  
  pre_tasks:
    - block:
      - name: Define variable to access existing storage stack info
        set_fact:
          nfs_stack: "{{ (hostvars[groups['openstack'][0]])['storage_stack_info'] }}"
      - name: Define variables for NFS role
        set_fact:
          nfs_servers: "{{ nfs_stack['nfs_servers'] }}"
          nfs_export: "{{ nfs_stack['nfs_export'] }}"
      when: storage_name is defined
  roles:
    - role: resmo.ntp

    - role: stackhpc.cluster-nfs
      nfs_enable:
        server: "{{ inventory_hostname in (groups['nfs'] | default([])) }}"
        clients: "{{ inventory_hostname in groups['compute'] or inventory_hostname in groups['login'] }}"
      nfs_server: "{{ (groups['nfs'] | default(nfs_servers)) | first }}"

- hosts:
    - login
    - compute
  become: yes
  pre_tasks:

    - name: Ensure user home dir root exists
      file:
        path: "{{ jasmin_homedir }}"
        state: directory
      run_once: true

  roles:
    # Run the user creation once to create the user home directories
    - role: singleplatform-eng.users
      users: "{{ jasmin_users }}"
      groups_to_create: "{{ jasmin_groups }}"
      run_once: true

    # Run the user creation again (without home dir) on all nodes
    - role: singleplatform-eng.users
      users: "{{ jasmin_users }}"
      groups_to_create: "{{ jasmin_groups }}"
      users_create_homedirs: false

        
- hosts:
    - login
    - compute
  become: yes
  pre_tasks:

    - name: Ensure the OpenHPC package repo rpm is present
      yum:
        name: "https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm"
        state: present

    - name: Ensure latest python is present
      yum:
        name: python
        state: latest

  roles:
    - role: stackhpc.openhpc
      openhpc_enable:
        control: "{{ inventory_hostname in groups['login'] }}"
        batch: "{{ inventory_hostname in groups['compute'] }}"
        runtime: true
      openhpc_cluster_name: "{{ cluster_name }}"
      openhpc_slurm_partitions: "{{ openhpc_slurm_partitions }}"
      openhpc_slurm_control_host: "{{ groups['login'] | first }}"
