---
#####
## Playbook that provisions and then configures a Kubernetes
## cluster on OpenStack
#####

# Do the configuration
- hosts: openstack
  tasks:
    - import_tasks: tasks/discover-gateway-ip.yml

# Provision the cluster infrastructure
- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      cluster_groups: "{{ cluster_groups_with_gw }}"

# Generate keystone trust token
- hosts: openstack
  tasks:
    - import_tasks: tasks/os-keystone-trust.yml
      when: cluster_state | lower == 'present'

# Do cluster setup for all hosts
- hosts: kube-masters,kube-workers
  roles:
    - role: jasmin.k8s/kubeadm
      kube_role: "{{ 'master' if inventory_hostname in groups['kube-masters'] else 'worker' }}"
      openstack_trust_id: "{{ hostvars[groups['openstack'] | first]['openstack_trust_id'] }}"
      openstack_project_id: "{{ hostvars[groups['openstack'] | first]['openstack_project_id'] }}"
      kubernetes_version: "{{ cluster_version }}"
      upgrade_system_packages: "{{ cluster_upgrade_system_packages | default(false) }}"
      when: cluster_state | lower == 'present'
  become: yes

# Install addons via the master
- hosts: kube-masters
  roles:
    - role: jasmin.k8s/helm
      when: cluster_state | lower == 'present'
    - role: jasmin.k8s/ingress_nginx
      when: cluster_state | lower == 'present'
    - role: jasmin.k8s/kubernetes_dashboard
      when: cluster_state | lower == 'present'
  become: yes

# Delete the bastion
- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      cluster_stack_update_only: true
      cluster_groups: "{{ cluster_groups_without_gw }}"
      when:
        - cluster_gw_group == 'ephemeral'
        - cluster_state | lower == 'present'
...
