---
#####
## Performs Kubernetes cluster configuration for any inventory that defines
## the groups "kube-masters" and "kube-workers"
#####

- import_playbook: os-keystone-trust.yml

# Do cluster setup for all hosts
- hosts: kube-masters,kube-workers
  vars: 
    cloud_provider: openstack
    openstack_trust_id: "{{ hostvars[groups['openstack'] | first]['openstack_trust_id'] }}"
    openstack_project_id: "{{ hostvars[groups['openstack'] | first]['openstack_project_id'] }}"
    kubernetes_version: "{{ cluster_version }}"
    upgrade_system_packages: "{{ cluster_upgrade_system_packages | default(false) }}"
  roles:
    - role: jasmin.k8s/kubeadm
      kube_role: "{{ 'master' if inventory_hostname in groups['kube-masters'] else 'worker' }}"
      become: yes

# Install addons via the master
- hosts: kube-masters
  roles:
    - role: jasmin.k8s/helm
    - role: jasmin.k8s/ingress_nginx
    - role: jasmin.k8s/kubernetes_dashboard
    - role: jasmin.pangeo-helm
      when: pangeo_infra_enable
  become: yes

# Delete the bastion
- hosts: openstack
  vars_files:
    - "vars/kube-masters{{ '-with-fip' if pangeo_infra_enable else '' }}.yml"
    - "vars/kube-workers.yml"
  roles:
    - role: jasmin.cluster-infra
      cluster_stack_update_only: true
      cluster_groups:
        - "{{ cluster_masters }}"
        - "{{ cluster_workers }}"
      when: not pangeo_infra_enable
