---
#####
## Playbook that provisions and then configures a Kubernetes
## cluster on OpenStack
#####

# Do the configuration
- import_playbook: discover-gateway-ip.yml

# Provision the cluster infrastructure
- hosts: openstack
  vars_files:
    - "vars/kube-masters{{ '-with-fip' if pangeo_infra_enable else '' }}.yml"
    - "vars/kube-workers.yml"
  roles:
    - role: jasmin.cluster-infra
      cluster_groups:
        - "{{ cluster_masters }}"
        - "{{ cluster_workers }}"
        - "{{ cluster_gw if pangeo_infra_enable else omit }}"

# Do the configuration
- import_playbook: k8s-infra-configure.yml
  when: cluster_state | lower == 'present'
...
