---
#####
## Performs Kubernetes cluster configuration for any inventory that defines
## the groups "kube-masters" and "kube-workers"
#####

# Do cluster setup for all hosts
- hosts: kube-masters,kube-workers
  #remote_user: root
  roles:
    - jasmin.k8s/kubeadm
  become: yes

# Install addons via the master
- hosts: kube-masters
  #remote_user: root
  roles:
    - jasmin.k8s/helm
    - jasmin.k8s/ingress_nginx
    - jasmin.k8s/kubernetes_dashboard
  become: yes
