---
- hosts: openstack
  tasks:
    - set_fact:
        cluster_masters:
          name: kube-masters
          user: "{{ cluster_deploy_user }}"
          node_resource: "Cluster::Node"
          nodenet_resource: "Cluster::NodeNet1"
          num_nodes: 1
          flavor: "{{ cluster_master_flavor | default('j3.medium') }}"
          root_volume_size: 0
        cluster_workers:
          name: kube-workers
          user: "{{ cluster_deploy_user }}"
          node_resource: "Cluster::Node"
          nodenet_resource: "Cluster::NodeNet1"
          num_nodes: "{{ cluster_num_workers }}"
          flavor: "{{ cluster_worker_flavor | default('j3.medium') }}"
          root_volume_size: 0
    - block:
        - name: Authenticate to the cloud and retrieve current project_id, user_id and auth_token
          os_keystone_trust:
            trustee_user_id: "{{ openstack_trustee_id }}"
            impersonation: true
            roles:
              - name: "{{ cluster_delegate_role }}"
          register: result
        - name: Set openstack_project_id, openstack_user_id and opestack_trust_id as fact
          set_fact:
            openstack_project_id: "{{ result.project_id }}"
            openstack_user_id: "{{ result.user_id }}"
            openstack_trust_id: "{{ result.trust_id }}"
      when:
        (openstack_trust_id is not defined or
        openstack_project_id is not defined or
        openstack_user_id is not defined)
...
