---
#####
## Performs Kubernetes cluster configuration for any inventory that defines
## the groups "kube-masters" and "kube-workers"
#####

# Generate openstack trustee credentials
- hosts: openstack
  tasks:
    - block:
        - name: Authenticate to the cloud and retrieve current project_id and trust_id for the input openstack_trustee_id
          os_keystone_trust:
            trustee_user_id: "{{ openstack_trustee_id }}"
            impersonation: true
            roles:
              - name: "{{ cluster_delegate_role }}"
          register: result
        - name: Set openstack_project_id and opestack_trust_id as fact
          set_fact:
            openstack_project_id: "{{ result.project_id }}"
            openstack_trust_id: "{{ result.trust_id }}"
      when:
        (openstack_trust_id is not defined or
        openstack_project_id is not defined)

# Do cluster setup for all hosts
- hosts: kube-masters,kube-workers
  vars: 
    cloud_provider: openstack
    openstack_trust_id: "{{ hostvars[groups['openstack'] | first]['openstack_trust_id'] }}"
    openstack_project_id: "{{ hostvars[groups['openstack'] | first]['openstack_project_id'] }}"
  roles:
    - role: jasmin.k8s/kubeadm
      kube_role: "{{ 'master' if inventory_hostname in groups['kube-masters'] else 'worker' }}"
  become: yes

# Install addons via the master
- hosts: kube-masters
  roles:
    - jasmin.k8s/helm
    - jasmin.k8s/ingress_nginx
    - jasmin.k8s/kubernetes_dashboard
  become: yes
