---
#####
## Playbook that provisions and then configures a Kubernetes
## cluster on OpenStack
#####

# Do the configuration
- import_playbook: discover-gateway-ip.yml
  when: cluster_state | lower == 'present'

# Provision the cluster infrastructure
- hosts: openstack
  vars_files:
    - vars/kube-masters.yml
    - vars/kube-workers.yml
  roles:
    - role: jasmin.cluster-infra
      cluster_groups:
        - "{{ cluster_masters }}"
        - "{{ cluster_workers }}"
        - "{{ cluster_gw }}"
  when: cluster_state | lower == 'present'

# Do the configuration
- import_playbook: k8s-infra-configure.yml
  when: cluster_state | lower == 'present'

# Delete the bastion
- hosts: openstack
  vars_files:
    - vars/kube-masters.yml
    - vars/kube-workers.yml
  roles:
    - role: jasmin.cluster-infra
      cluster_stack_update_only: true
      cluster_groups:
        - "{{ cluster_masters }}"
        - "{{ cluster_workers }}"
