---
#####
## Playbook that provisions and then configures a Kubernetes
## cluster on OpenStack
#####

# Provision the cluster infrastructure
- hosts: openstack
  pre_tasks:
    - import_tasks: tasks/install-dependencies.yml
    - import_tasks: tasks/discover-gateway-ip.yml
  roles:
    - role: jasmin.cluster-infra
      cluster_gw_group: "{{ k8s_gw_group if cluster_fixed_ip is defined else cluster_gw.name }}"
      cluster_groups: "{{ k8s_groups_fip if cluster_fixed_ip is defined else k8s_groups_no_fip + [cluster_gw] }}"
  post_tasks:
    # Generate keystone trust token
    - import_tasks: tasks/os-keystone-trust.yml
      when: cluster_state | default('present') | lower == 'present'

# Do cluster setup for all hosts
#   If cluster_state=absent, this play will be skipped as the inventory will be empty
- hosts: kube-masters,kube-workers
  roles:
    - role: jasmin.k8s/kubeadm
      kube_role: "{{ 'master' if inventory_hostname in groups['kube-masters'] else 'worker' }}"
      openstack_trust_id: "{{ hostvars[groups['openstack'] | first]['openstack_trust_id'] }}"
      openstack_project_id: "{{ hostvars[groups['openstack'] | first]['openstack_project_id'] }}"
      kubernetes_version: "{{ cluster_version }}"
      upgrade_system_packages: "{{ cluster_upgrade_system_packages | default(false) }}"
  become: yes

# Install addons via the master
#   If cluster_state=absent, this play will be skipped as the inventory will be empty
- hosts: kube-masters
  roles:
    - jasmin.k8s/helm
    - jasmin.k8s/ingress_nginx
    - jasmin.k8s/kubernetes_dashboard
  become: yes

# Delete the bastion
- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      cluster_stack_update_only: true
      cluster_groups: "{{ k8s_groups_no_fip }}"
      when:
        - cluster_fixed_ip is not defined
        - cluster_state | default('present') | lower == 'present'
