---
# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of baremetal compute node instances, and configure it
# for a NFS server 
- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      cluster_auth_type: "{{ openstack_auth_type }}"
      cluster_auth: "{{ openstack_auth }}"
      cluster_network: "caastest-U-internal"
      cluster_name: "{{ bastion_name }}"
      cluster_groups: "{{ bastion_groups }}"
      cluster_deploy_user: "{{ bastion_deploy_user }}"
      cluster_net: "{{ bastion_net }}"
      cluster_gw_group: "{{ bastion_gw_group }}"

- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      cluster_auth_type: "{{ openstack_auth_type }}"
      cluster_auth: "{{ openstack_auth }}"
      cluster_network: "caastest-U-internal"
      cluster_name: "{{ nfs_name }}"
      cluster_groups: "{{ nfs_groups }}"
      cluster_deploy_user: "{{ nfs_deploy_user }}"
      cluster_net: "{{ nfs_net }}"
      cluster_gw_group: "{{ bastion_gw_group }}"
- hosts:
    - cluster
  become: true
  tasks:
    - import_tasks: cluster-firewalld.yml 

- import_playbook: nfs.yml

- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      cluster_auth_type: "{{ openstack_auth_type }}"
      cluster_auth: "{{ openstack_auth }}"
      cluster_network: "caastest-U-internal"
      cluster_name: "{{ bastion_name }}"
      cluster_groups: "{{ bastion_groups }}"
      cluster_deploy_user: "{{ bastion_deploy_user }}"
      cluster_net: "{{ bastion_net }}"
      cluster_gw_group: "{{ bastion_gw_group }}"
      cluster_state: absent
