---

- hosts: openstack
  tasks:
    - import_tasks: tasks/install-dependencies.yml

    # Add the identity stack to the cluster and configure it as the gateway
    - include_role:
        name: jasmin.cluster-infra
      vars:
        cluster_name: "{{ identity_stack_name }}"
        cluster_stack_update: false
        cluster_gw_group: "{{ identity_gw_group_name }}"

    # Provision the cluster infrastructure
    - import_tasks: tasks/infra/provision.yml
      vars:
        cluster_groups: "{{ nfs_groups }}"
        cluster_tag: "{{ cluster_type.storage }}"

# Gather facts for all hosts
- hosts: cluster
  tasks: []

- hosts: nfs_servers
  become: true
  tasks:
    - import_tasks: tasks/network/firewall.yml
    - include: tasks/util/upgrade_os_packages.yml
    # Join the nfs_servers to the FreeIPA realm
    - include_tasks: tasks/identity/freeipa/client.yml

# Set the permissions for the cluster in FreeIPA
- hosts: freeipa_servers
  become: true
  tasks:
    - include_tasks: tasks/identity/freeipa/cluster_permissions.yml
  vars:
    # We don't need a group to permit users access to these hosts
    create_users_group: false

- hosts: nfs_servers
  become: true
  pre_tasks:
    # Prevent nfs-server from failing to start after reboot: IPv6 is disabled via
    # sysctl in the JASMIN CentOS 7 image, but initramfs doesn't include this
    # sysctl setting. This prevents rpcbind (on which nfs-server depends) from
    # starting on boot. See https://access.redhat.com/solutions/2798411 for more
    # details. Unfortunately the Red Hat solution is incomplete, as dracut doesn't
    # include /etc/sysctl* by default, so we modify dracut.conf before rebuilding.
    - name: Add sysctl configuration to dracut.conf
      lineinfile:
        path: /etc/dracut.conf
        line: install_items="/etc/sysctl.conf /etc/sysctl.d/*"
      register: dracut_configure

    - name: Rebuild initramfs
      command: dracut -f
      when: dracut_configure is changed
  roles:
    - role: stackhpc.cluster-nfs
      become: true
      nfs_enable:
        server: true
        clients: false
      nfs_disk_location: "{{ cluster_attached_volumes.0.device }}"
