---

# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of baremetal compute node instances, and configure it
# for a NFS server

- hosts: openstack
  tasks:
    - import_tasks: tasks/install-dependencies.yml
    - import_tasks: tasks/infra/provision.yml
      vars:
        cluster_groups: "{{ nfs_groups }}"
        cluster_tag: "{{ cluster_type.storage }}"
    - name: Add servers to nfs_servers group
      add_host:
        name: "{{ item }}"
        groups: nfs_servers
      loop: "{{ groups.get('server', []) }}"
    - name: Load nfs_servers variables
      include_vars: group_vars/nfs_servers

- hosts: cluster
  become: true
  tasks:
    - import_tasks: cluster-hosts.yml
    - import_tasks: cluster-firewalld.yml

- import_playbook: playbooks/nfs.yml

- hosts: nfs_servers
  tasks:
    - include: tasks/update.yml

- hosts: openstack
  tasks:
    - import_tasks: tasks/infra/cleanup-gateway.yml
      vars:
        cluster_groups: "{{ nfs_groups }}"
        cluster_tag: "{{ cluster_type.storage }}"
