---
# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of baremetal compute node instances, and configure it
# for a NFS server 

- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      cluster_auth_type: "{{ openstack_auth_type }}"
      cluster_auth: "{{ openstack_auth }}"
      cluster_network: "caastest-U-internal"
      cluster_name: "{{ nfs_name }}"
      cluster_groups: "{{ nfs_groups + [cluster_gw] }}"
      cluster_deploy_user: "{{ nfs_deploy_user }}"
      cluster_net: "{{ nfs_net }}"
      cluster_tag: "{{ nfs_tag }}"
  tasks:
    - name: add nfs cluster to nfs_servers group
      add_host:
       name: "{{ item }}"
       groups: nfs_servers
      loop: "{{ groups['server'] }}"

- hosts:
    - cluster
  become: true
  tasks:
    - import_tasks: cluster-hosts.yml 
    - import_tasks: cluster-firewalld.yml 

- import_playbook: nfs.yml

- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      cluster_auth_type: "{{ openstack_auth_type }}"
      cluster_auth: "{{ openstack_auth }}"
      cluster_network: "caastest-U-internal"
      cluster_name: "{{ nfs_name }}"
      cluster_groups: "{{ nfs_groups }}"
      cluster_deploy_user: "{{ nfs_deploy_user }}"
      cluster_net: "{{ nfs_net }}"
      cluster_tag: "{{ nfs_tag }}"
      cluster_stack_update_only: true

  # Hack pending outcome of https://github.com/ansible/ansible/pull/53757
  tasks:
    - name: Fixup stack tags
      command: "openstack stack update --existing --tags {{ nfs_tag }} {{ nfs_name }}"
