---

# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of baremetal compute node instances, and configure it
# for a NFS server

- hosts: openstack
  tasks:
    - import_tasks: tasks/install-dependencies.yml
    - import_tasks: tasks/infra/provision.yml
      vars:
        cluster_groups: "{{ nfs_groups }}"
        cluster_tag: "{{ cluster_type.storage }}"

- hosts: cluster
  become: true
  tasks:
    - import_tasks: tasks/cluster-hosts.yml
    - import_tasks: tasks/cluster-firewalld.yml

- import_playbook: playbooks/nfs.yml

- hosts: nfs_servers
  tasks:
    - include: tasks/update.yml

- hosts: openstack
  tasks:
    - import_tasks: tasks/infra/cleanup-gateway.yml
      vars:
        cluster_groups: "{{ nfs_groups }}"
        cluster_tag: "{{ cluster_type.storage }}"
