---
- import_playbook: k8s-infra.yml
  vars:
    cluster_gw_group: kube-masters

# Install addons via the master
- hosts: kube-masters
  roles:
    - role: jasmin.pangeo-helm
      pangeo_admin_users: ["{{ pangeo_username }}"]
      pangeo_users: ["{{ pangeo_username }}"]
  become: yes
...
