---
#####
## Playbook that provisions and then configures a Kubernetes
## cluster on OpenStack
#####

# Provision the cluster infrastructure
- hosts: openstack
  vars_files:
    - vars/kube-masters-with-fip.yml
    - vars/kube-workers.yml
  roles:
    - role: jasmin.cluster-infra
      cluster_groups:
        - "{{ cluster_masters }}"
        - "{{ cluster_workers }}"

# Do the configuration
- import_playbook: k8s-infra-configure.yml
  when: cluster_state | lower == 'present'

# Install pangeo helm chart
- hosts: kube-masters
  vars_files:
    - vars/kube-masters.yml
    - vars/kube-workers.yml
  roles:
    - name: jasmin.pangeo-helm
      become: yes
...
