---
#####
## Playbook that provisions and then configures a Kubernetes
## cluster on OpenStack
#####

# Set cluster variables
- import_playbook: pangeo-infra-variables.yml
  when: cluster_state | lower == 'present'

# Provision the cluster infrastructure
- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      cluster_groups:
        - "{{ cluster_masters }}"
        - "{{ cluster_workers }}"

# Do the configuration
- import_playbook: k8s-infra-configure.yml
  when: cluster_state | lower == 'present'

# Install pangeo helm chart
- hosts: kube-masters
  roles:
    - name: jasmin.pangeo-helm
      become: yes
...
