---

- hosts: openstack
  tasks:
    - import_tasks: tasks/install-dependencies.yml

    # Add the identity stack to the cluster and configure it as the gateway
    - include_role:
        name: jasmin.cluster-infra
      vars:
        cluster_name: "{{ identity_stack_name }}"
        cluster_stack_update: false
        cluster_gw_group: "{{ identity_gw_group_name }}"

    # Add the storage stack to the cluster
    - include_role:
        name: jasmin.cluster-infra
      vars:
        cluster_name: "{{ storage_name }}"
        cluster_stack_update: false

    # Provision the SLURM infrastructure
    - import_tasks: tasks/infra/provision.yml
      vars:
        # These are the groups to use when no fixed IP is given
        cluster_groups: "{{ slurm_groups_no_ip }}"
        # These are the groups to use when a fixed IP is given
        cluster_groups_fixed_ip: "{{ slurm_groups_fixed_ip }}"
        # Tag to assign to  the cluster
        cluster_tag: "{{ cluster_type.slurm }}"

- hosts: cluster
  become: true
  tasks:
    - import_tasks: tasks/network/hosts.yml

- hosts: slurm
  become: true
  tasks:
    - include_tasks: tasks/network/firewall.yml
    - include_tasks: tasks/slurm/upgrade_os_packages.yml
      vars:
        openhpc_slurm_control_host: "{{ groups['slurm_login'] | first }}"
    # Join the hosts to the FreeIPA realm
    - include_tasks: tasks/identity/freeipa/client.yml

# Set the permissions for the cluster in FreeIPA
- hosts: freeipa_servers
  become: true
  tasks:
    - include_tasks: tasks/identity/freeipa/cluster_permissions.yml
  vars:
    # Users in the cluster group should get SSH access
    permit_user_ssh: true

- hosts: slurm
  become: true
  pre_tasks:
    # Mount the storage
    - name: Mount shared storage
      include_tasks: tasks/storage/client.yml

    - name: Install OpenHPC repository
      yum:
        name: "{{ openhpc_repo_url }}"
        state: present
  roles:
    - role: stackhpc.openhpc
      openhpc_enable:
        control: "{{ inventory_hostname in groups['slurm_login'] }}"
        batch: "{{ inventory_hostname in groups['slurm_compute'] }}"
        runtime: true
      openhpc_cluster_name: "{{ cluster_name }}"
      # Put all the compute nodes into a single partition
      openhpc_slurm_partitions:
        - name: "compute"
      openhpc_slurm_control_host: "{{ groups['slurm_login'] | first }}"

# - import_playbook: validation.yml
#   when:
#     - validation is defined
#     - validation | bool
