---

# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of baremetal compute node instances, and configure it
# for a NFS server

- hosts: openstack
  tasks:
    - name: Add servers to nfs_servers group
      add_host:
        name: another_host
        groups:
          - nfs_servers

- import_playbook: another_playbook.yml
