- hosts: openstack
  tasks:
    - add_host:
        name: another_host
        groups: another_group
        ansible_host: 127.0.0.1
        ansible_connection: local
        testvar: value

- hosts: another_group
  tasks:
    - debug: var=testvar

- hosts: openstack
  tasks:
    - debug: var=testvar
    - debug: msg="{{ groups['another_group'] }}"
    - debug: msg="{{ groups['another_group'] | first }}"
    - debug: msg="{{ hostvars.keys() }}"
    - debug: msg="{{ hostvars[groups['another_group'] | first]['nfs_export'] }}"
