---
# Playbook to update all packages on Slurm login and compute nodes
# The compute nodes are drained before applying updates and optionally
# rebooting if there is a new kernel.

- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      cluster_network: "caastest-U-internal"
      cluster_name: "{{ slurm_name }}"
      cluster_groups: "{{ slurm_groups }}"
      cluster_deploy_user: "{{ slurm_deploy_user }}"
      cluster_net: "{{ slurm_net }}"

- hosts: login
  gather_facts: no
  tasks:
  - import_tasks: tasks/drain.yml
    vars:
      nodes_to_drain: "{{ groups['compute'] }}"

- hosts:
    - login
    - compute
  become: yes
  tasks:
    - import_tasks: tasks/openhpc-repos.yml
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: Check for reboot hint
      shell: LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1 {sub(/kernel-/,""); print $1}'); if [ $LAST_KERNEL != "{{ ansible_kernel }}" ]; then echo 'reboot'; else echo 'no'; fi
      ignore_errors: true
      register: reboot_hint
    - name: Rebooting
      reboot:
      when: reboot_hint.stdout.find("reboot") != -1

- hosts: login
  gather_facts: no
  tasks:
  - import_tasks: tasks/resume.yml
    vars:
      nodes_to_resume: "{{ groups['compute'] }}"
