---
# Playbook to update all packages on Slurm login and compute nodes
# The compute nodes are drained before applying updates and optionally
# rebooting if there is a new kernel.

- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      cluster_network: "caastest-U-internal"
      cluster_name: "{{ slurm_name }}"
      cluster_groups: "{{ slurm_groups }}"
      cluster_deploy_user: "{{ slurm_deploy_user }}"
      cluster_net: "{{ slurm_net }}"

- hosts: login
  gather_facts: no
  tasks:
  - import_tasks: tasks/drain.yml
    vars:
      nodes_to_drain: "{{ groups['compute'] }}"

- hosts:
    - login
    - compute
  become: yes
  tasks:
    - import_tasks: tasks/openhpc-repos.yml
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: Check if reboot is required
      command: needs-restarting -r
      changed_when: false
      failed_when: false
      register: reboot_required
    - name: Rebooting
      reboot:
      when: reboot_required.rc != 0

- hosts: login
  gather_facts: no
  tasks:
  - import_tasks: tasks/resume.yml
    vars:
      nodes_to_resume: "{{ groups['compute'] }}"
