---
# Playbook to update all packages on Slurm login and compute nodes
# The compute nodes are drained before applying updates and optionally
# rebooting if there is a new kernel.

- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      cluster_network: "caastest-U-internal"
      cluster_name: "{{ slurm_name }}"
      cluster_groups: "{{ slurm_groups }}"
      cluster_deploy_user: "{{ slurm_deploy_user }}"
      cluster_net: "{{ slurm_net }}"

- hosts:
    - compute
  serial: "{{ concurrent_compute_update | default(1) }}"
  tasks:
    - include: tasks/update_node.yml drain=true

- hosts:
    - login
  tasks:
    - include: tasks/update_node.yml
