# End to end test using Heptio Sonobuoy: 
# https://github.com/heptio/sonobuoy
- hosts: kube-masters
  vars:
    sonobuoy_quick_test: true
  environment:
    PATH: >-
      {{ ansible_env.HOME }}/go/bin:{{ ansible_env.PATH }}
  handlers:

    - name: Cleanup sonobuoy
      command: sonobuoy delete --wait
      register: delete_status
      changed_when: delete_status.stderr is not search('already deleted')

  tasks:

    - rpm_key:
        key: https://mirror.go-repo.io/centos/RPM-GPG-KEY-GO-REPO
        state: present
      become: yes

    - name: Download yum repository
      get_url:
        url: https://mirror.go-repo.io/centos/go-repo.repo
        dest: /etc/yum.repos.d/go-repo-CentOS.repo
      become: yes

    - name: Install golang
      yum:
        name:
          - golang
          - git
        state: latest
      become: yes

    - name: Install sonobuoy
      command: go get -u -v github.com/heptio/sonobuoy
      register: install_sonobuoy
      changed_when: install_sonobuoy.stderr_lines | length > 1

    - name: Run cleanup handler in case it already exists
      command: /bin/true
      notify: Cleanup sonobuoy
    - meta: flush_handlers

    - name: Run sonobuoy 
      command: >
        sonobuoy run --wait --mode {{ "quick" if sonobuoy_quick_test | bool else "conformance" }}

    - name: Retrieve results
      command: sonobuoy retrieve
      register: result_path

    - name: Get e2e status
      command: >
        sonobuoy e2e {{ result_path.stdout }}
      register: status
      changed_when: false

    - name: Fail and dump status if errorenous
      fail:
        msg: >
          {{ status.stdout }}
      when: >
        status.stdout is not search('failed tests: 0')

    - name: Delete result file
      file:
        path: >-
          {{ ansible_env.PWD }}/{{ result_path.stdout }}
        state: absent
      notify: Cleanup sonobuoy
