---

- name: jasmin.cluster-infra
  src: https://github.com/cedadev/jasmin-cluster-infra-ansible
  version: multi-stack
- name: jasmin.rke
  src: https://github.com/cedadev/rke-ansible
  version: master
- name: jasmin.helm
  src: https://github.com/cedadev/helm-ansible
  version: master
- src: resmo.ntp
- src: stackhpc.beegfs
- name: stackhpc.gluster-cluster
  src: https://github.com/stackhpc/ansible-role-gluster-cluster.git
- name: stackhpc.openhpc
  version: v0.3.0
- name: stackhpc.cluster-nfs
  src: https://github.com/stackhpc/ansible-role-cluster-nfs
  version: master
- name: stackhpc.cluster-infra
  src: https://github.com/stackhpc/ansible-role-cluster-infra
  version: newton-backport
