---
- name: Install FreeIPA packages
  yum:
    name:
      - freeipa-server
      - bind
      - bind-dyndb-ldap
    state: latest

# This is required by ipa-server-install if IPv6 is enabled in the kernel
- name: Enable IPv6 for loopback interface
  ansible.posix.sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: "0"

- name: Generate Directory Server password
  include_tasks: tasks/util/persistent_random_fact.yml
  vars:
    fact_name: freeipa_ds_password
    random_fact_bytes: 32

- name: Configure FreeIPA server
  command: >
    ipa-server-install
      --unattended
      --realm {{ freeipa_realm | quote }}
      --domain {{ freeipa_realm | lower | quote }}
      --ds-password {{ ansible_local.freeipa_ds_password | quote }}
      --admin-password {{ freeipa_admin_password | quote }}
  register: ipa_server_install
  changed_when: ipa_server_install.rc == 0
  failed_when: >
    ipa_server_install.rc != 0 and
    'IPA server is already configured' not in ipa_server_install.stderr

# "novalocal" isn't a valid email domain, which prevents the creation of new users
# So set something else - it doesn't have to be a real email
# Also set the default login shell to bash
- name: Configure user defaults
  community.general.identity.ipa.ipa_config:
    ipadefaultemaildomain: jasmin.cloud
    ipadefaultloginshell: /bin/bash
    ipa_host: "{{ ansible_fqdn }}"
    ipa_pass: "{{ freeipa_admin_password }}"

# ipa_config doesn't have an option to configure the default home directory
# We also need to use Kerberos authentication
- block:
    - name: Get Kerberos ticket
      shell: kinit admin <<< {{ freeipa_admin_password | quote }}

    - name: Configure default home directory
      command: ipa config-mod --homedirectory={{ jasmin_homedir }}
      register: ipa_config_mod
      changed_when: ipa_config_mod.rc == 0
      failed_when: >
        ipa_config_mod.rc != 0 and
        'no modifications to be performed' not in ipa_config_mod.stderr

    - name: Set password expiry for admin user
      # Just pick a date ages in the future
      command: ipa user-mod admin --setattr=krbPasswordExpiration=21000101000000Z
      register: ipa_user_mod
      changed_when: ipa_user_mod.rc == 0
      failed_when: >
        ipa_user_mod.rc != 0 and
        'no modifications to be performed' not in ipa_user_mod.stderr
  always:
    - name: Destroy Kerberos ticket
      command: kdestroy

- name: Create allow all rule for admins
  community.general.identity.ipa.ipa_hbacrule:
    cn: allow_all_admins
    description: Allow admins to access any host from any host
    state: enabled
    hostcategory: all
    servicecategory: all
    usergroup: [admins]
    ipa_host: "{{ ansible_fqdn }}"
    ipa_pass: "{{ freeipa_admin_password }}"

- name: Disable default blanket allow all rule
  community.general.identity.ipa.ipa_hbacrule:
    cn: allow_all
    state: disabled
    ipa_host: "{{ ansible_fqdn }}"
    ipa_pass: "{{ freeipa_admin_password }}"
