---

- name: Install FreeIPA packages
  yum:
    name:
      - freeipa-server
      - bind
      - bind-dyndb-ldap
    state: latest

# This is required by ipa-server-install if IPv6 is enabled in the kernel
- name: Enable IPv6 for loopback interface
  sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: 0

- name: Configure FreeIPA server
  command: >
    ipa-server-install
      --unattended
      --realm {{ freeipa_realm | quote }}
      --domain {{ freeipa_realm | lower | quote }}
      --ds-password {{ freeipa_admin_password | quote }}
      --admin-password {{ freeipa_admin_password | quote }}
  register: ipa_server_install
  changed_when: ipa_server_install.rc == 0
  failed_when: >
    ipa_server_install.rc != 0 and
    'IPA server is already configured' not in ipa_server_install.stderr

- name: Set bash as the default login shell
  ipa_config:
    ipadefaultloginshell: /bin/bash
    ipa_host: "{{ ansible_fqdn }}"
    ipa_pass: "{{ freeipa_admin_password }}"

- name: Create allow all rule for admins
  ipa_hbacrule:
    cn: allow_all_admins
    description: Allow admins to access any host from any host
    state: enabled
    hostcategory: all
    servicecategory: all
    usergroup: [admins]
    ipa_host: "{{ ansible_fqdn }}"
    ipa_pass: "{{ freeipa_admin_password }}"

- name: Disable default blanket allow all rule
  ipa_hbacrule:
    cn: allow_all
    state: disabled
    ipa_host: "{{ ansible_fqdn }}"
    ipa_pass: "{{ freeipa_admin_password }}"
