---

# Make sure that there is a line in /etc/hosts for each host in the play
- name: Populate /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^{{ hostvars[host].ansible_default_ipv4.address | regex_replace("\.", "\.") }}'
    line: "{{ hostvars[host].ansible_default_ipv4.address }} {{ hostvars[host].ansible_fqdn }} {{ hostvars[host].ansible_hostname }}"
  loop: "{{ ansible_play_hosts }}"
  loop_control:
    loop_var: host
