---

- block:
    - name: Query existing stack for its output
      os_stack_outputs:
        stack: "{{ cluster_name }}"
      ignore_errors: true

    - name: Extract output of existing ephemeral bastion
      vars:
        query: "node_groups[?name=='{{ cluster_gw_group }}'].nodes[0]"
      set_fact:
        fip_stack_output: "{{ openstack_stack_outputs | json_query(query) | first or omit }}"
      when: openstack_stack_outputs is defined
  when: cluster_fixed_ip is not defined

- name: Find gateway floating IP
  os_network_find_fip:
    floating_network: "{{ cluster_floating_network }}"
    ip: "{{ cluster_fixed_ip | default(omit) }}"
  register: fip_network
  when: fip_stack_output is not defined

- name: Set gateway IP facts
  set_fact:
    cluster_gw_fip_id: "{{ (fip_stack_output | default(fip_network)).id }}"
    cluster_gw_fip_ip: "{{ (fip_stack_output | default(fip_network)).ip }}"
