---
# Ansible tasks to drain a Slurm compute node. Waits for the compute node to be
# drained for up to a day by default.
#
# Variables:
# - node_to_drain: compute node to drain
# - drain_timeout: seconds to wait for node to drain, default is 86400.

- name: Drain compute node
  become: yes
  command: "scontrol update nodename={{ node_to_drain }} state=DRAIN reason='maintenance'"

- name: Check node has drained
  command: "sinfo --noheader --Node --format='%N' --states=DRAINED"
  register: drained_nodes
  until: "drained_nodes.stdout_lines is superset([node_to_drain])"
  delay: 10
  retries: "{{ (drain_timeout|default(86400) / 10)|int }}"
