---
# Ansible tasks to drain Slurm compute nodes. Waits for compute nodes to be
# drained for up to a day.
#
# Variables:
# - nodes_to_drain: list of compute nodes to drain
# - drain_timeout: seconds to wait for nodes to drain, default is 86400.

- name: Drain compute nodes
  become: yes
  command: "scontrol update nodename={{ item }} state=DRAIN reason='maintenance'"
  # If called with hosts: <group>, execute only on the first host of the group
  run_once: true
  with_items: "{{ nodes_to_drain }}"

- name: Check nodes have drained
  command: "sinfo --noheader --Node --format='%N' --states=DRAINED"
  register: drained_nodes
  until: "drained_nodes.stdout_lines is superset(nodes_to_drain)"
  delay: 10
  retries: "{{ (drain_timeout|default(86400) / 10)|int }}"
