---

- name: Get Ansible venv path
  set_fact:
    ansible_venv_path: "{{ lookup('env', 'ANSIBLE_VENV_PATH') }}"

- block:
    - name: Ensure yum dependencies are installed
      yum:
        name:
          - gcc
          - python2-devel
        state: latest

    - name: Ensure Python dependencies are installed
      pip:
        requirements: "{{ playbook_dir }}/requirements.txt"
        virtualenv: "{{ ansible_venv_path }}"

    
      
  when: "ansible_venv_path | length > 0"

- name: Install community collection
    ansible.builtin.shell: ansible-galaxy collection install community.general

