---

- name: Get Ansible venv path
  set_fact:
    ansible_venv_path: "{{ lookup('env', 'ANSIBLE_VENV_PATH') }}"

- block:
    - name: Ensure python-jinja2 is removed from system since this conflicts with pip installed version.
      yum:
        name: python-jinja2
        state: absent

    - name: Ensure yum dependencies are installed
      yum:
        name:
          - gcc
          - python2-devel
        state: latest

    - name: Ensure Python dependencies are installed
      pip:
        requirements: "{{ playbook_dir }}/requirements.txt"
        virtualenv: "{{ ansible_venv_path }}"
  when: "ansible_venv_path | default(None, true)"
