---

- name: Get Ansible venv path
  set_fact:
    ansible_venv_path: "{{ lookup('env', 'ANSIBLE_VENV_PATH') }}"

- block:
    - name: Ensure yum dependencies are installed
      apt-get:
        name:
          - gcc
          - python2-devel
        state: latest

#  when: "ansible_venv_path | length > 0"

- name: Install community collection
  command: ansible-galaxy collection install community.general


