- name: Get stack outputs
  os_stack_outputs:
    stack: "{{ storage_name }}"

- name: Export storage information from stack outputs
  set_fact:
    storage_stack_info: "{{ openstack_stack_outputs['info'] | reject('equalto', '') | map('from_json') | selectattr('storage_type', 'defined') | first }}"

- set_fact:
    server_list: "{{ storage_stack_info[storage_stack_info['storage_type'] + '_servers'] }}"

- set_fact:
    group_name: "{{ storage_stack_info['group'] }}"
  when: "'group' in storage_stack_info"

- set_fact:
    group_name: "{{ storage_stack_info['storage_type'] + '_servers' }}"
  when: "'group' not in storage_stack_info"

- set_fact:
    storage_type: "{{ storage_stack_info['storage_type'] }}"
  delegate_facts: yes
  delegate_to: localhost

- name: Create storage server group and hosts
  add_host:
    name: "{{ item }}"
    groups: "{{ group_name }}"
  with_items: "{{ server_list }}"

- name: Set Ansible facts on storage server hosts
  set_fact:
    ansible_eth0:
      ipv4:
        address: "{{ item }}"
  delegate_facts: yes
  delegate_to: "{{ item }}"
  with_items:
    - "{{ server_list }}"

- name: Set Ansible variables from stack on storage server hosts
  set_fact:
    "{{ item[1].key }}": "{{ item[1].value }}"
  delegate_facts: yes
  delegate_to: "{{ item[0] }}"
  with_nested:
    - "{{ server_list }}"
    - "{{ storage_stack_info['vars'] | dict2items }}"
