---

beegfs_groups:
  - "{{ beegfs_group_mds }}"
  - "{{ beegfs_group_oss }}"

beegfs_group_mds:
  name: "mds"
  flavor: "{{ beegfs_mds_flavor | default('j1.small') }}"
  num_nodes: 1
  nodenet_resource: "Cluster::NodeNet1"
  additional_volumes:
    - name: mds
      size: "{{ beegfs_mds_volume_size | default(2) }}"
      device: /dev/sdb
  inventory_groups:
    - beegfs_servers
    - beegfs_mds

beegfs_group_oss:
  name: "oss"
  flavor: "{{ beegfs_oss_flavor | default('j2.small') }}"
  num_nodes: "{{ beegfs_oss_num_nodes | default(3) }}"
  nodenet_resource: "Cluster::NodeNet1"
  additional_volumes:
    - name: oss
      size: "{{ beegfs_oss_volume_size | default(10) }}"
      device: /dev/sdb
  inventory_groups:
    - beegfs_servers
    - beegfs_oss
