---

beegfs_cluster_info:
  storage_type: "beegfs"
  beegfs_servers: "$PRIMARY_IPS"
  group: mds
  vars: {}

beegfs_groups:
  - "{{ beegfs_group_mds }}"
  - "{{ beegfs_group_oss }}"

beegfs_group_mds:
  name: "mds"
  flavor: "{{ beegfs_mds_flavor | default('j1.small') }}"
  user: "{{ cluster_deploy_user }}"
  num_nodes: 1
  root_volume_size: "{{ beegfs_mds_volume_size | default(2) }}"
  node_resource: "Cluster::NodeWithVolume"
  nodenet_resource: "Cluster::NodeNet1"
  info: "{{ beegfs_cluster_info | to_json }}"

beegfs_group_oss:
  name: "oss"
  flavor: "{{ beegfs_oss_flavor | default('j2.small') }}"
  user: "{{ cluster_deploy_user }}"
  num_nodes: "{{ beegfs_oss_num_nodes | default(3) }}"
  root_volume_size: "{{ beegfs_oss_volume_size | default(10) }}"
  node_resource: "Cluster::NodeWithVolume"
  nodenet_resource: "Cluster::NodeNet1"
