---

freeipa_gw_group_name: "proxy"

freeipa_group_proxy:
  name: "{{ freeipa_gw_group_name }}"
  node_resource: "Cluster::Node"
  nodenet_resource: "Cluster::NodeNet1"
  num_nodes: 1
  flavor: "{{ freeipa_server_flavor | default('j2.small') }}"
  root_volume_size: 0
  inventory_groups:
    - freeipa_proxies

freeipa_group_server:
  name: server
  node_resource: "Cluster::Node"
  nodenet_resource: "Cluster::NodeNet1"
  num_nodes: 1
  flavor: "{{ freeipa_server_flavor | default('j2.small') }}"
  root_volume_size: 0
  inventory_groups:
    - freeipa_servers

freeipa_groups_fixed_ip:
  - "{{ freeipa_group_proxy | combine(cluster_gw_fip_mixin) }}"
  - "{{ freeipa_group_server }}"

freeipa_groups_no_ip:
  - "{{ freeipa_group_server }}"
