---

gluster_groups:
  - "{{ gluster_group_servers }}"

gluster_group_servers:
  name: "server"
  flavor: "{{ gluster_server_flavor | default('j1.small') }}"
  num_nodes: "{{ gluster_num_nodes | default(3) }}"
  nodenet_resource: "Cluster::NodeNet1"
  additional_volumes:
    - name: data
      size: "{{ gluster_volume_size | default(10) }}"
      device: /dev/sdb
  inventory_groups:
    - gluster_servers
  facts:
    # These are things that clients need to know
    gluster_cluster_transport_interface: eth0
    gluster_cluster_transport_mode: tcp
    gluster_cluster_volume_name: "{{ cluster_name }}"
