---

deploy_gw_group_name: "deploy-gw"

deploy_gw_group:
  name: "{{ deploy_gw_group_name }}"
  nodenet_resource: "Cluster::NodeNet1WithPreallocatedFIP"
  nodenet_fips:
    - uuid: "{{ cluster_fip_id }}"
      ip: "{{ cluster_fip_ip }}"
  num_nodes: 1
  flavor: "j1.tiny"

cluster_fip_mixin:
  nodenet_resource: "Cluster::NodeNet1WithPreallocatedFIP"
  nodenet_fips:
    - uuid: "{{ cluster_fip_id }}"
      ip: "{{ cluster_fip_ip }}"
