---

identity_gw_group_name: "gateway"

default_gateway_external_domain: "{{ cluster_fixed_ip | replace('.', '-') }}.sslip.io"

identity_group_gateway:
  name: "{{ identity_gw_group_name }}"
  nodenet_resource: "Cluster::NodeNet1"
  num_nodes: 1
  flavor: "{{ identity_gateway_flavor | default('j2.small') }}"
  inventory_groups:
    - identity_servers
    - gateway_servers
  facts:
    gateway_external_domain: "{{ gateway_external_domain | default(default_gateway_external_domain, true) }}"

identity_group_freeipa_server:
  name: freeipa
  nodenet_resource: "Cluster::NodeNet1"
  num_nodes: 1
  flavor: "{{ freeipa_server_flavor | default('j2.small') }}"
  inventory_groups:
    - identity_servers
    - freeipa_servers
  facts:
    freeipa_admin_password: "{{ admin_password }}"
    freeipa_realm: "TENANT.LOCAL"

identity_group_keycloak_server:
  name: keycloak
  nodenet_resource: "Cluster::NodeNet1"
  num_nodes: 1
  flavor: "{{ keycloak_server_flavor | default('j2.small') }}"
  inventory_groups:
    - identity_servers
    - keycloak_servers
  facts:
    keycloak_oidc_issuer_url: "https://{{ identity_group_gateway.facts.gateway_external_domain }}/auth/realms/master"

identity_groups_fixed_ip:
  - "{{ identity_group_gateway | combine(cluster_fip_mixin) }}"
  - "{{ identity_group_freeipa_server }}"
  - "{{ identity_group_keycloak_server }}"

identity_groups_no_ip:
  - "{{ identity_group_gateway }}"
  - "{{ identity_group_freeipa_server }}"
  - "{{ identity_group_keycloak_server }}"
