---

k8s_gw_group_name: "master"

default_kubernetes_dashboard_domain: "dashboard.{{ cluster_fixed_ip | replace('.', '-') }}.sslip.io"

k8s_group_masters:
  name: "{{ k8s_gw_group_name }}"
  nodenet_resource: "Cluster::NodeNet1"
  num_nodes: 1
  flavor: "{{ cluster_master_flavor }}"
  #root_volume_size: "{{ cluster_root_volume_size }}"
  inventory_groups:
    - rke_hosts
    - rke_masters
  facts:
    kubernetes_dashboard_domain: "{{ kubernetes_dashboard_domain | default(default_kubernetes_dashboard_domain, true) }}"

k8s_group_workers:
  name: "worker"
  nodenet_resource: "Cluster::NodeNet1"
  num_nodes: "{{ cluster_num_workers }}"
  flavor: "{{ cluster_worker_flavor }}"
  #root_volume_size: "{{ cluster_root_volume_size }}"
  inventory_groups:
    - rke_hosts
    - rke_workers

k8s_groups_fixed_ip:
  - "{{ k8s_group_masters | combine(cluster_fip_mixin) }}"
  - "{{ k8s_group_workers }}"

k8s_groups_no_ip:
  - "{{ k8s_group_masters }}"
  - "{{ k8s_group_workers }}"
