---

nfs_cluster_info:
  storage_type: "nfs"
  nfs_servers: "$PRIMARY_IPS"
  vars:
    nfs_export: "/srv/home"

nfs_groups:
  - "{{ nfs_group_server }}"

nfs_group_server:
  name: "nfs_servers"
  flavor: "{{ nfs_server_flavor | default('j1.small') }}"
  user: "{{ cluster_deploy_user }}"
  num_nodes: 1
  root_volume_size: "{{ nfs_volume_size | default(10) }}"
  node_resource: "Cluster::NodeWithVolume" 
  nodenet_resource: "Cluster::NodeNet1"
  info: "{{ nfs_cluster_info | to_json }}"
