---
# The storage size (in gigabytes) for the NFS export.
nfs_volume_size: 10

nfs_cluster_info:
  storage_type: "nfs"
  nfs_servers: "$PRIMARY_IPS"
  vars:
    nfs_export: "/srv/home"

nfs_groups:
  - "{{ nfs_group_server }}"

nfs_group_server:
  name: "server"
  flavor: "j1.small"
  image: "{{ cluster_image }}"
  user: "{{ cluster_deploy_user }}"
  num_nodes: 1
  root_volume_size: "{{ nfs_volume_size }}"
  node_resource: "Cluster::NodeWithVolume" 
  nodenet_resource: "Cluster::NodeNet1"
  info: "{{ nfs_cluster_info | to_json }}"
