---

nfs_cluster_info:
  storage_type: "nfs"
  nfs_servers: "$PRIMARY_IPS"
  vars:
    nfs_export: "/srv/home"

nfs_groups:
  - "{{ nfs_group_server }}"

nfs_group_server:
  name: "server"
  flavor: "{{ nfs_server_flavor | default('j1.small') }}"
  num_nodes: 1
  nodenet_resource: "Cluster::NodeNet1"
  additional_volumes:
    - name: data
      size: "{{ nfs_volume_size | default(10) }}"
  info: "{{ nfs_cluster_info | to_json }}"
  inventory_groups:
    - nfs_servers
