---

nfs_groups:
  - "{{ nfs_group_server }}"

nfs_group_server:
  name: "server"
  flavor: "{{ nfs_server_flavor | default('j1.small') }}"
  num_nodes: 1
  nodenet_resource: "Cluster::NodeNet1"
  additional_volumes:
    - name: data
      size: "{{ nfs_volume_size | default(10) }}"
      device: /dev/sdb
  inventory_groups:
    - nfs_servers
  facts:
    nfs_export: /srv
