---

# Nginx doesn't resolve using /etc/hosts, but we require this because
# we need to contact the FreeIPA server using it's FQDN
# To get round it, we run dnsmasq and point Nginx to use 127.0.0.1 as resolver
# - name: Install dnsmasq
#   yum:
#     name: dnsmasq
#     state: latest

# - name: Ensure dnsmasq is started
#   service:
#     name: dnsmasq
#     state: restarted
#     enabled: yes

- name: Install Nginx
  yum:
    name: nginx
    state: latest

- name: Create Nginx SSL directory
  file:
    path: /etc/nginx/ssl
    state: directory

- name: Create Ephemeral Diffie-Helman parameters file
  command: openssl dhparam -dsaparam -out /etc/nginx/ssl/dhparam.pem 4096
  args:
    creates: /etc/nginx/ssl/dhparam.pem

- name: Generate self-signed SSL certificate
  command: >
    openssl req
      -new -nodes -x509 -days 3650 -extensions v3_ca
      -keyout /etc/nginx/ssl/server.key
      -out /etc/nginx/ssl/server.crt
      -subj "/CN={{ ansible_default_ipv4.address }}"
  args:
    creates: /etc/nginx/ssl/server.crt

- name: Install main Nginx configuration
  template:
    src: nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Install FreeIPA site configuration
  template:
    src: freeipa/nginx_site.conf.j2
    dest: /etc/nginx/conf.d/freeipa.conf
  vars:
    ssl_certificate_path: /etc/nginx/ssl/server.crt
    ssl_private_key_path: /etc/nginx/ssl/server.key

- name: Ensure Nginx is started
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: Open HTTP(S) ports in firewall
  firewalld:
    service: "{{ service }}"
    state: enabled
    immediate: yes
    permanent: yes
  loop:
    - http
    - https
  loop_control:
    loop_var: service
