---

- name: Install FreeIPA packages
  yum:
    name:
      - freeipa-server
      - bind
      - bind-dyndb-ldap
    state: latest

# This is required by ipa-server-install if IPv6 is enabled in the kernel
- name: Enable IPv6 for loopback interface
  sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: 0

- name: Configure FreeIPA server
  command: >
    ipa-server-install
      --unattended
      --realm {{ freeipa_realm | quote }}
      --domain {{ freeipa_domain | quote }}
      --ds-password {{ freeipa_ds_password | quote }}
      --admin-password {{ freeipa_admin_password | quote }}
  register: ipa_server_install
  failed_when: >
    ipa_server_install.rc != 0 and
    'IPA server is already configured' not in ipa_server_install.stderr
  changed_when: ipa_server_install.rc == 0
