---
# This name is used for the Heat stack and as a prefix for the
# cluster node hostnames.
gluster_name: gluster

gluster_deploy_user: 'centos'

gluster_net: "caastest-U-internal"

gluster_tag: "storage"

gluster_groups:
  - "{{ gluster_group_servers }}"

gluster_group_servers:
  name: "server"
  flavor: "j1.small"
  image: "centos-7-20190104"
  user: "centos"
  num_nodes: 3
  root_volume_size: 10
  node_resource: "Cluster::NodeWithVolume" 
  nodenet_resource: "Cluster::NodeNet1"
