---
# Common k8s cluster configuration used by k8s-infra.yml playbook
cluster_name: k8s
cluster_version: "1.13"
cluster_state: present
cluster_network: caastest-U-internal
cluster_num_workers: 3
# cluster_fixed_ip:
# cluster_keypair:
# openstack_trustee_id:
# openstack_trustee_password:

# Additional configuration used by pangeo-infra.yml playbook
pangeo_hosts: [ "pangeo.kgz.sh" ]
pangeo_users: [ "admin" ]
pangeo_admin_users: [ "admin" ]
pangeo_password: secretnomore
...
