---
# This name is used for the Heat stack and as a prefix for the
# cluster node hostnames.
cluster_name: test

cluster_deploy_user: 'centos'

cluster_net: "caastest-U-internal"

cluster_groups:
  - "{{ slurm_login }}"
  - "{{ slurm_compute }}"
  - "{{ cluster_nfs }}"

cluster_gw_group: "login"

slurm_login:
  name: "login"
  flavor: "j1.small"
  image: "centos-7-20190104"
  user: "centos"
  num_nodes: 1
  root_volume_size: 0
  node_resource: "Cluster::Node" 
  nodenet_resource: "Cluster::NodeNet1WithPreallocatedFIP" 
  nodenet_fips:
    - uuid: "fbd8781c-0917-41a3-8a66-ecaf0f05826a"
      ip: "192.171.139.250"

slurm_compute:
  name: "compute"
  flavor: "j2.tiny"
  image: "centos-7-20190104"
  user: "centos"
  num_nodes: 2
  root_volume_size: 0
  node_resource: "Cluster::Node" 
  nodenet_resource: "Cluster::NodeNet1" 
  nodenet_fips: []

cluster_nfs:
  name: "nfs"
  flavor: "j1.small"
  image: "centos-7-20190104"
  user: "centos"
  num_nodes: 1
  root_volume_size: 20
  node_resource: "Cluster::NodeWithVolume" 
  nodenet_resource: "Cluster::NodeNet1" 
  nodenet_fips: []

# Node group assignments for cluster roles.
# These group assignments are appended to the cluster inventory file.
# The names of these roles are cross-referenced to groups referred to
# in playbooks in the ansible/ directory.
cluster_roles:
  - name: "nfs_server"
    groups:
      - "{{ cluster_nfs }}"
  - name: "nfs_client"
    groups: 
      - "{{ slurm_login }}"
      - "{{ slurm_compute }}"
  - name: "control"
    groups: 
      - "{{ slurm_login }}"
  - name: "login"
    groups: 
      - "{{ slurm_login }}"
  - name: "batch"
    groups: 
      - "{{ slurm_compute }}" 


# Define a list of SLURM partitions to create.
openhpc_slurm_partitions: 
  - name: caas
    groups:
      - "{{ slurm_compute }}"

# A list of OpenHPC runtime libraries to install on compute and control nodes
openhpc_packages:
  - strace
  - flex
  - bison
  - cfitsio
  - cfitsio-devel
  - cfitsio-docs
  - wcslib
  - wcslib-utils
  - wcslib-devel
  - wcstools
  - ncurses
  - ncurses-devel
  - readline
  - readline-devel
  - boost
  - boost-devel
  - boost-python
  - boost-math
  - boost-doc
  # OpenHPC bits
  - hdf5-gnu-ohpc
  - phdf5-gnu-mvapich2-ohpc
  - gnu-compilers-ohpc
  - mvapich2-gnu-ohpc
  - openmpi-gnu-ohpc
  - imb-gnu-mvapich2-ohpc
  - imb-gnu-openmpi-ohpc
  - fftw-gnu-mvapich2-ohpc
  - fftw-gnu-openmpi-ohpc
  - openblas-gnu-ohpc
  - scalapack-gnu-mvapich2-ohpc
  - gsl-gnu-ohpc
  - python-scipy-gnu-mvapich2-ohpc
  - python-scipy-gnu-openmpi-ohpc
  - python34
  - python34-devel
  - python-virtualenv
  - infiniband-diags
  - emacs
  - vim

# kdump not required
kdump_enable: false

jasmin_homedir: "/jasmin"
jasmin_group_name: "jasmin"
jasmin_groups:
  - name: "{{ jasmin_group_name }}"
    gid: 2000

jasmin_users: 
  - username: "hsilk"
    groups: [ "{{ jasmin_group_name }}" ]
    name: "Holly Silk <holly@stackhpc.com>"
    home: "{{jasmin_homedir}}/hsilk"
    uid: 3390
    ssh_key:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsysvkkEbEDSx/xcgA9fEmd6KTD4wBlEEeo9dqM2TEbwxg3Pl5nuji44dXzl0+01fwDR7Zn8I79XYZMgVaAQl9wRK6x7jLnJWpLo2+jhC1gu2108P7yWWplpFS40LHRAU1SDMvNfDM2drNx3T3tmoNlr7HnO8URnBslWtjNCAbdY4B2p7jJmdCfQdtvxpzUDVMilihXxXZ8016WYQYdDQmUTyGWn+oHBDegpKPodFFswRhTavFO/OGbACTZ18W6Sv57ShzI0DrKPmU9uSs7PyZJuazn2ZDEWa330w2gpmG7+1GsKibsgxTNVGbp/FuSDv1G1FY8kDTbVNNH1gzUkbj hsilk@Hollys-MacBook-Air.local"
  - username: "stig"
    groups: [ "{{ jasmin_group_name }}" ]
    name: "Stig Telfer <stig@stackhpc.com>"
    home: "{{jasmin_homedir}}/stig"
    uid: 3391
    ssh_key:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDkXbp+OEyRoAtLPvmNJoLQJJKbjfWXVT3xyyLArzbKDNUkC8mdOUJDFPOJj91CEKKPd1x+6ys6EzJ8zFpfTQYkULClUE3XVx5q7ZMdQE3wROK+++z4RCcKrTgArd2wp5cfluMbwgp+HThuv+hdEvpEmltiALWk8wocPS6lHQmpq7AA+oB798ErNGITjfOdBbAmzcJ/Qba6y8J/ksShBDyn+dnhOT/M9wLsJaO5lh2wRqO6WxLZ6N5tlQZyyXAxBsphi+4u4gG1FiCdu7CClQr+zxEGHOnYxtbSa0X51zINxFKQAljI0IXYFJ3/7hmjkGhd1bGdXvVIqFOQdKGNFvXR stig@skellig.local"

