---
# This name is used for the Heat stack and as a prefix for the
# cluster node hostnames.
nfs_name: nfs

nfs_deploy_user: 'centos'

nfs_net:
  - { net: "caastest-U-internal", subnet: "caastest-U-internal" }

nfs_groups:
  - "{{ nfs_group_server }}"
#cluster_gw_group: "login"

nfs_group_server:
  name: "server"
  flavor: "j1.small"
  image: "centos-7-20190104"
  user: "centos"
  num_nodes: 1
  root_volume_size: 20
  node_resource: "Cluster::NodeWithVolume" 
  nodenet_resource: "Cluster::NodeNet1"

