---
nfs_deploy_user: 'centos'

nfs_groups:
  - "{{ nfs_group_server }}"

#cluster_gw_group: "login"
nfs_tag: "storage"

nfs_group_server:
  name: "server"
  flavor: "j1.small"
  image: "centos-7-20190104"
  user: "centos"
  num_nodes: 1
  root_volume_size: 10
  node_resource: "Cluster::NodeWithVolume" 
  nodenet_resource: "Cluster::NodeNet1"

