---

# These tasks use local facts to manage a persistent random fact,
# i.e. the value is random but persists across playbook runs

- block:
    - name: Ensure facts.d directory exists
      file:
        path: /etc/ansible/facts.d
        state: directory

    - name: Produce random data
      command: openssl rand -hex {{ random_fact_bytes }}
      register: openssl_rand

    - name: Write facts.d file
      copy:
        content: "{{ openssl_rand.stdout | trim | to_json }}"
        dest: /etc/ansible/facts.d/{{ fact_name }}.fact
        mode: "u=rw,g=,o="

    - name: Reload facts
      setup:
  when: fact_name not in ansible_local
