{% set default_pangeo_domain = "pangeo." + (cluster_fixed_ip | replace('.', '-')) + ".sslip.io" %}
jupyterhub:
  # Authenticate using the FreeIPA LDAP database
  # We use LDAP because the LDAP authenticator supports controlling access by group membership
  # The oauthenticator doesn't understand OpenID Connect so can't use the groups claim
  auth:
    type: ldap
    ldap:
      server:
        # Use the IP address as the DNS resolution isn't always reliable
        address: "{{ hostvars[groups.freeipa_servers | first].ansible_default_ipv4.address }}"
      dn:
        templates:
          - "uid={username},cn=users,cn=accounts,{{ freeipa_ldap_domain }}"
      allowedGroups:
        - "cn=admins,cn=groups,cn=accounts,{{ freeipa_ldap_domain }}"
        - "cn={{ pangeo_notebook_users_group }},cn=groups,cn=accounts,{{ freeipa_ldap_domain }}"
    admin:
      access: true
      users: [admin]
  hub:
    db:
      type: sqlite-pvc
      pvc:
        storageClassName: standard
    services:
      dask-gateway:
        apiToken: "{{ ansible_local.pangeo_dask_gateway_api_token }}"
    # Disable hub networkpolicy support for now as it doesn't play nicely with dask-gateway
    # This is fixed on master but not in a release as of 04/01/2021
    # https://github.com/dask/helm-chart/issues/142
    networkPolicy:
      enabled: false
  singleuser:
    image:
      name: pangeo/pangeo-notebook
      tag: "2021.01.11"
    startTimeout: 1000
    storage:
      type: dynamic
      capacity: "{{ pangeo_notebook_storage | default(10) }}Gi"
      dynamic:
        storageClass: standard
    cpu:
      limit: {{ pangeo_notebook_cpu | default(1) }}
      guarantee: {{ pangeo_notebook_cpu | default(1) }}
    memory:
      limit: "{{ pangeo_notebook_mem | default(2) }}G"
      guarantee: "{{ pangeo_notebook_mem | default(2) }}G"
  # Disable the userScheduler and userPlaceholder as they only make sense
  # on clusters which autoscale
  scheduling:
    userScheduler:
      enabled: false
    userPlaceholder:
      enabled: false
  proxy:
    service:
      type: ClusterIP
    secretToken: "{{ ansible_local.pangeo_secret_token }}"
  ingress:
    enabled: true
    hosts: ["{{ pangeo_domain | default(default_pangeo_domain, true) }}"]
    # Get a certificate from the letsencrypt issuer
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - hosts: ["{{ pangeo_domain | default(default_pangeo_domain, true) }}"]
        secretName: pangeo-tls

dask-gateway:
  gateway:
    auth:
      jupyterhub:
        apiToken: "{{ ansible_local.pangeo_dask_gateway_api_token }}"
    # Use the Pangeo image for Dask schedulers and workers
    backend:
      image:
        name: pangeo/pangeo-notebook
        tag: "2021.01.11"
