---

- name: Install Nginx
  yum:
    name: nginx
    state: latest

- name: Create Nginx SSL directory
  file:
    path: /etc/nginx/ssl
    state: directory

- name: Create Ephemeral Diffie-Helman parameters file
  command: openssl dhparam -dsaparam -out /etc/nginx/ssl/dhparam.pem 4096
  args:
    creates: /etc/nginx/ssl/dhparam.pem

- name: Generate self-signed SSL certificate
  command: >
    openssl req
      -new -nodes -x509 -days 3650 -extensions v3_ca
      -keyout /etc/nginx/ssl/server.key
      -out /etc/nginx/ssl/server.crt
      -subj "/CN={{ ansible_default_ipv4.address }}"
  args:
    creates: /etc/nginx/ssl/server.crt

- name: Install main Nginx configuration
  template:
    src: templates/identity/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Install FreeIPA site configuration
  template:
    src: templates/identity/freeipa_site.conf.j2
    dest: /etc/nginx/conf.d/freeipa.conf

- name: Ensure Nginx is started
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: Open HTTP(S) ports in firewall
  firewalld:
    service: "{{ service }}"
    state: enabled
    immediate: yes
    permanent: yes
  loop:
    - http
    - https
  loop_control:
    loop_var: service
