---
# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of baremetal compute node instances, and configure it
# for a SLURM partition
- hosts: openstack

  roles:
#    - role: stackhpc.cluster-infra
    - role: jasmin.cluster-infra
      vars:
        cluster_network: "caastest-U-internal"
        cluster_groups:
          - name: test
            num_nodes: 1
            flavor: j2.small

#      cluster_name: "{{ cluster_name }}"
#      cluster_params:
#        cluster_prefix: "{{ cluster_name }}"
#        cluster_keypair: "{{ cluster_keypair }}"
#        cluster_net: "{{ cluster_net }}"
#      cluster_roles: "{{ cluster_roles }}"
      # jasmin.cluster-infra params
