---
# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of baremetal compute node instances, and configure it
# for a NFS server 

- hosts: cluster
  become: true

  roles:
    - role: stackhpc.cluster-nfs
      nfs_enable:
        server: "{{ inventory_hostname in groups['nfs_server'] }}" 
        clients:  "{{ inventory_hostname in groups['nfs_clients'] }}" 
      nfs_server: "{{ groups['nfs_server'] | first }}"
