---

# Check if kubectl is available on the controller
# If it isn't, we won't attempt to drain and we will do all hosts in one batch
- name: Check if kubectl is available
  command: which kubectl
  run_once: true
  register: kubectl_available
  ignore_errors: yes

# If kubectl isn't available, just upgrade packages on all hosts
- include_tasks: tasks/util/upgrade_os_packages.yml
  when: kubectl_available is failed

# If kubectl is available process the hosts in batches, attempting to drain before upgrading
- include_tasks: drain_and_upgrade.yml
  when:
    - cluster_upgrade_system_packages | default(false) | bool
    - kubectl_available is succeeded
    - inventory_hostname in batch_hosts
  # Make sure we take out no more than 20% of hosts at once
  loop: "{{ ansible_play_hosts | batch([(ansible_play_hosts | count) / 2 | round(0, 'floor') | int, 1] | max) | list }}"
  loop_control:
    loop_var: batch_hosts
