---

# These tasks configure Keycloak to use FreeIPA as the user store
# We assume that the host has already been joined to the FreeIPA realm

- name: Install dependencies
  yum:
    name:
      - sssd-dbus
      - jna
      - "{{ keycloak_libdbus_rpm }}"
    state: latest
  register: keycloak_sssd_deps

- name: Update SSSD configuration file
  ini_file:
    path: /etc/sssd/sssd.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    # Set the cache timeout for users and groups at 5 mins
    - section: "domain/{{ freeipa_realm | lower }}"
      option: ldap_user_extra_attrs
      value: "mail:mail, sn:sn, givenname:givenname, telephoneNumber:telephoneNumber"
    - section: sssd
      option: services
      value: "nss, sudo, pam, ssh, ifp"
    - section: ifp
      option: allowed_uids
      value: "root, keycloak"
    - section: ifp
      option: user_attributes
      value: "+mail, +telephoneNumber, +givenname, +sn"
  register: keycloak_sssd_configure

- name: Restart SSSD
  service:
    name: sssd
    state: restarted
  when: keycloak_sssd_configure is changed

- name: Create Keycloak PAM configuration file
  copy:
    content: |
      auth    required   pam_sss.so
      account required   pam_sss.so
    dest: /etc/pam.d/keycloak
  register: keycloak_pam_configure

- name: Restart Keycloak
  service:
    name: keycloak
    state: restarted
  when: >
    keycloak_sssd_deps is changed or
    keycloak_sssd_configure is changed or
    keycloak_pam_configure is changed

- name: Wait for Keycloak API to be available
  uri:
    url: "http://localhost:8080/auth/"
    status_code: 200
  register: keycloak_api
  until: keycloak_api is succeeded
  retries: 60
  delay: 5

- name: Check if SSSD user federation has been enabled
  command: >
    /opt/keycloak/latest/bin/kcadm.sh get components
      --query name=sssd
      --no-config
      --server http://localhost:8080/auth
      --realm master
      --user {{ keycloak_admin_user }}
      --password {{ keycloak_admin_password | quote }}
  register: keycloak_sssd_enabled

- name: Enable SSSD user federation for realm
  command: >
    /opt/keycloak/latest/bin/kcadm.sh create components
      --set name=sssd
      --set providerType=org.keycloak.storage.UserStorageProvider
      --set providerId=sssd
      --no-config
      --server http://localhost:8080/auth
      --realm master
      --user {{ keycloak_admin_user }}
      --password {{ keycloak_admin_password | quote }}
  when: "(keycloak_sssd_enabled.stdout | from_json | count) == 0"

- name: Log in with FreeIPA admin user to force sync of groups
  command: >
    /opt/keycloak/latest/bin/kcadm.sh config credentials
      --server http://localhost:8080/auth
      --realm master
      --user admin
      --password {{ freeipa_admin_password }}

- name: Grant the admins group from FreeIPA admin access in Keycloak
  command: >
    /opt/keycloak/latest/bin/kcadm.sh add-roles
      --gname admins
      --rolename admin
      --no-config
      --server http://localhost:8080/auth
      --realm master
      --user {{ keycloak_admin_user }}
      --password {{ keycloak_admin_password | quote }}
