---
# This playbook uses the Ansible OpenStack modules to create a cluster
# for a BeeGFS server 

- hosts:
    -  beegfs_servers
    -  beegfs_clients
  roles:
    # Note: The BeeGFS clients are likely to be drawn from across a multi-stack
    # platform deployment. This playbook assumes the existence of a meta-group,
    # beegfs_clients, which contains all clients in the cluster.
    - role: stackhpc.beegfs
      beegfs_enable:
        admon: false
        mgmt: "{{ cluster_name+'_mds' in groups and inventory_hostname in groups[cluster_name + '_mds'] }}"
        meta: "{{ cluster_name+'_mds' in groups and inventory_hostname in groups[cluster_name + '_mds'] }}"
        oss: "{{ cluster_name+'_oss' in groups and inventory_hostname in groups[cluster_name + '_oss'] }}"
        tuning: "{{ cluster_name+'_oss' in groups and inventory_hostname in groups[cluster_name + '_oss'] }}"
        client: "{{ 'beegfs_clients' in groups and inventory_hostname in groups['beegfs_clients'] }}"
      beegfs_oss:
      - dev: "/dev/sdb"
        port: 8003
      # FIXME: doesn't work yet...
      beegfs_mgmt_host: "{{ cluster_name+'_mds' in groups | ternary (groups[cluster_name + '_mds'], hostvars[groups['openstack'][0]].storage_stack_info[storage_servers_group]) | first }}"
      beegfs_client:
      - path: "{{ jasmin_homedir }}"
        port: 8004
      beegfs_fstype: "xfs"
      beegfs_force_format: false
      beegfs_interfaces: ["eth0"]
      beegfs_rdma: false
      beegfs_state: present
