---
# Prevent Gluster servers from failing to start after reboot: IPv6 is disabled
# via sysctl in the JASMIN CentOS 7 image, but initramfs doesn't include this
# sysctl setting. This prevents rpcbind (on which gluster depends) from
# starting on boot. See https://access.redhat.com/solutions/2798411 for more
# details. Unfortunately the Red Hat solution is incomplete, as dracut doesn't
# include /etc/sysctl* by default, so we modify dracut.conf before rebuilding.
- hosts:
    - gluster_servers:&cluster
  become: true
  tasks:
    - name: Add sysctl configuration to dracut.conf
      lineinfile:
        path: /etc/dracut.conf
        line: install_items="/etc/sysctl.conf /etc/sysctl.d/*"
      notify:
        - Rebuild initramfs
  handlers:
    - name: Rebuild initramfs
      command: dracut -f

- hosts:
    - gluster_servers:&cluster
    - gluster_clients:&cluster
  roles:
    - role: stackhpc.gluster-cluster
      become: true
      gluster_cluster_volume_name: "{{ hostvars[groups['gluster_servers'] | first]['gluster_cluster_volume_name'] | default(cluster_name) }}"
      gluster_cluster_storage_group_name: gluster_servers
      gluster_cluster_block_devices: 
        - sdb
      gluster_cluster_transport_interface: eth0
      gluster_cluster_transport_mode: tcp
      gluster_cluster_volume_options:
        cluster.nufa: 'on'
      gluster_enable:
        servers: "{{ inventory_hostname in groups['gluster_servers'] }}"
        clients: "{{ 'gluster_clients' in groups and inventory_hostname in groups['gluster_clients'] }}"
      gluster_cluster_server: "{{ groups['gluster_servers'] | first }}"
      gluster_cluster_server_export: "/srv/home"
      gluster_cluster_client_mntpoint: "{{ jasmin_homedir }}"
