---
# This playbook uses the Ansible OpenStack modules to create a cluster
# using a number of baremetal compute node instances, and configure it
# for a NFS server.

# Prevent nfs-server from failing to start after reboot: IPv6 is disabled via
# sysctl in the JASMIN CentOS 7 image, but initramfs doesn't include this
# sysctl setting. This prevents rpcbind (on which nfs-server depends) from
# starting on boot. See https://access.redhat.com/solutions/2798411 for more
# details. Unfortunately the Red Hat solution is incomplete, as dracut doesn't
# include /etc/sysctl* by default, so we modify dracut.conf before rebuilding.
- hosts:
    # Intersect NFS servers with the cluster group so this runs when the main
    # stack is an NFS cluster, but not when the group is defined from an
    # external storage stack.
    - nfs_servers:&cluster
  become: true
  tasks:
    - name: Add sysctl configuration to dracut.conf
      lineinfile:
        path: /etc/dracut.conf
        line: install_items="/etc/sysctl.conf /etc/sysctl.d/*"
      notify:
        - Rebuild initramfs
  handlers:
    - name: Rebuild initramfs
      command: dracut -f

- hosts: cluster
  roles:
    # Note: The NFS clients are likely to be drawn from across a multi-node
    # platform deployment. This playbook assumes the existence of a meta-group,
    # nfs_clients, which contains all clients in the cluster.
    - role: stackhpc.cluster-nfs
      become: true
      nfs_enable:
        server: "{{ 'nfs_servers' in groups and inventory_hostname in groups['nfs_servers'] }}"
        clients:  "{{ 'nfs_clients' in groups and inventory_hostname in groups['nfs_clients'] }}"
      nfs_server: "{{ groups['nfs_servers'] | first }}"
      nfs_export: "{{ hostvars[groups['nfs_servers'] | first]['nfs_export'] }}"
      nfs_client_mnt_point: "{{ jasmin_homedir }}"
